//import '@babel/runtime/regenerator'
//import 'react-hot-loader/patch'
//import 'webpack-hot-middleware/client?reload=true'
import './index.html'
import './main.css'
import './app'
import './nav.css'